language: generic

before_install:
  - sudo apt-get install fonts-font-awesome

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.10;
    fi
  # Install biber if required for compiling the references.
  # Biber 2.5 is required for tectonic 0.1.8
  - conda install -c malramsay biber==2.5 --yes
  - conda info -a
  # Workaround until tectonic 0.1.11 is available
  - sudo mkdir -p ~/.config/Tectonic/
  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script: # Change working directory each time so including files will work. Change back so the pdfs can be found for deployment. This way, building multiple files goes well.
 - cd $TRAVIS_BUILD_DIR
 - cp $TRAVIS_BUILD_DIR/config/config.tex $TRAVIS_BUILD_DIR/config.tex
 # Run tectonic once to generate intermediate files
 - tectonic --keep-intermediates --reruns 0 ./main.tex
 # If a bcf file exists run biber to compile references
 - if [ -f "main.bcf" ]; then biber main; fi

 # Final run of tectonic to create output
 - tectonic ./main.tex --print
