sudo: required
language: generic
services: docker

before_script:
  - cp $TRAVIS_BUILD_DIR/config.tex.sample $TRAVIS_BUILD_DIR/config.tex

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
