language: generic
before_install:
  - openssl aes-256-cbc -K $encrypted_5f210af7f267_key -iv $encrypted_5f210af7f267_iv
    -in github_key.enc -out github_key -d
  - chmod 600 github_key
  - eval $(ssh-agent -s)
  - ssh-add github_key
  - sudo apt-get install fonts-font-awesome
install:
  - git clone git@github.com:thechunk/resume-config.git $TRAVIS_BUILD_DIR/config
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
    channels conda-forge; conda config --set always_yes yes; conda install tectonic==0.1.10;
    fi
  - conda install -c malramsay biber==2.5 --yes
  - conda info -a
  - sudo mkdir -p ~/.config/Tectonic/
  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\""
    | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
    - "$HOME/miniconda"
    - "$HOME/.cache/Tectonic"
script:
  - cd $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/config/config.tex $TRAVIS_BUILD_DIR/config.tex
  - tectonic --keep-intermediates --reruns 0 ./main.tex
  - if [ -f "main.bcf" ]; then biber main; fi
  - tectonic ./main.tex --print
deploy:
  provider: releases
  api_key:
    secure: 2hfCjsowQIAvIn8nd5Uje01yjKYLNErYvXDgj8Swo6HselsdK0EmC+7RJHzouo7RfdVQqWId4ccIFe63pggh2fh+ilZG4Z7GrrnzMKXYau1IEUQ6/goRLLqr6kuz6lws1rS9kofZMOt4oIeqodDq8F6dkO+r5ek3W95BIJsWpDnnMVV2Dj6h4IPfj4Hdz2TUZRJ0JHuBI8qbZWGO9Dx5EBm3AQ1Ybm40p3RekHJosDRrG+U9jkKeRUNVshBWXtX/lDwyA82XDr6U2jXey9SMzZ6GFx8ThCr2DPDVk76y+nhblziMYJbBP5fTjnzPlUScyxD38ZBKFJQ7eARsdO1lrINKpQ3clCP4Vy5iAl71kq2oVBaHCBDxr/GI4rWiy9+ar+JSWlH4Ewv4yPN5roKkP48c5gmPmURwz8GpRunceq249mKlBJ24qHHXeOJzDWnCQldEPrnpXTBXfmPC40rlFLYoTo/GyXNf8mz92Rh9gEPzEuNpOs7aVQmZUm3vR2w9g0x5IQ5cqzK3pJHu+gEr7bfO4EXN2zrfomWxTnclsiqGDGEgw4qwzZ6cczVUII6Q87waOmsRZ4muruhB3Ne/P8WNSIejhnb8l6oUf2lqj1sdwwkC25ANQQ6CCYeXM//pYjty2QEzgrA0zqUpTf4aF9YfPgp3gTwdRcum7vsguks=
  file: ./main.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
